### ISSUE TITLE
correct_format_profile_yml.html appears to be missing

### ISSUE THREAD

**Issue by OliverWoolland** [ElixirTeSS/bioschemas-validator#1]
testYmlToDictCorrect in test_units.py fails as correct_format_profile_yml.html is not present

**Comment by 03c** [comment]
Is this the file: https://github.com/ElixirTeSS/bioschemas-validator/blob/main/test/profile_lib/correct_format_profile_yml.html

**Comment by OliverWoolland** [comment]
Yep! Thanks for that
